spring.application.name=SistemaPago
server.port=8081
spring.datasource.url=jdbc:postgresql://ep-round-water-abt324em-pooler.eu-west-2.aws.neon.tech/users_db?sslmode=require&channel_binding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_26GiHkNtyWms
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
