services:
  gateway:
    build: 
      context: ./Gateway_Service
      dockerfile: Dockerfile
    container_name: gateway-service
    ports:
      - "8080:8080"
    environment:
      JWT_SECRET: "vcGaq5k1m0VMQrjqzNoCRtHhS/+HecujQ30kr8PfSXc="
      USER_SERVICE_URL: "http://user-service:8081"
      PAYMENT_SERVICE_URL: "http://payment-service:8082"
    depends_on:
      user-service:
        condition: service_started
      payment-service:
        condition: service_started
    networks:
      - microservices-network

  user-service:
    build: 
      context: ./User_Services
      dockerfile: Dockerfile
    container_name: user-service
    ports:
      - "8081:8081"
    environment:
      JWT_SECRET: "vcGaq5k1m0VMQrjqzNoCRtHhS/+HecujQ30kr8PfSXc="
      SPRING_DATASOURCE_URL: ${SPRING_USERDB_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: "org.postgresql.Driver"
    networks:
      - microservices-network

  payment-service:
    build: 
      context: ./Payments_Services
      dockerfile: Dockerfile
    container_name: payment-service
    ports:
      - "8082:8082"
    environment:
      JWT_SECRET: "vcGaq5k1m0VMQrjqzNoCRtHhS/+HecujQ30kr8PfSXc="
      USER_SERVICE_URL: "http://user-service:8081"
      SPRING_DATASOURCE_URL: ${SPRING_PAYMENTDB_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: "org.postgresql.Driver"
    networks:
      - microservices-network

networks:
  microservices-network:
    driver: bridge